In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [7]:
## Introduccion a Tensors

#scalar
scalar = torch.tensor(7)
scalar #Objeto tipo tensor

tensor(7)

In [8]:
scalar.ndim #Devuelve las dimensiones del tensor

0

In [9]:
scalar.item() #Devuelve el elementos como integer

7

In [10]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [15]:
# Matrix
MATRIX = torch.tensor([[7,7],
                      [8,8]])
MATRIX

tensor([[7, 7],
        [8, 8]])

In [16]:
MATRIX.ndim

2

In [17]:
MATRIX[0]

tensor([7, 7])

In [23]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [24]:
TENSOR.ndim

3

In [25]:
TENSOR.shape

torch.Size([1, 3, 3])

In [26]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [28]:
### LOS TENSORs te devuelven matrices al indexar, las matrices te devuelven vectores y los vectores devuelven scalares