In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


## Introduccion a Tensors


In [3]:

#scalar
scalar = torch.tensor(7)
scalar #Objeto tipo tensor

tensor(7)

In [4]:
scalar.ndim #Devuelve las dimensiones del tensor

0

In [5]:
scalar.item() #Devuelve el elementos como integer

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([[7,7],
                      [8,8]])
MATRIX

tensor([[7, 7],
        [8, 8]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 7])

In [12]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
### LOS TENSORs te devuelven matrices al indexar, las matrices te devuelven vectores y los vectores devuelven scalares

## Random Tensors

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [17]:
# Create a random tensor of shape/size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5285, 0.2619, 0.8226, 0.4974],
        [0.3874, 0.1766, 0.0529, 0.6234],
        [0.8235, 0.8523, 0.5511, 0.9895]])

In [18]:
# Create a random tensor with similar shape to an imagen tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)

## Zeros and Ones

In [19]:
### Create a tensor of all zeros
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
### Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype #Default tensor type

torch.float32

## Create a range of tensor and tensors-like

In [22]:
# Use torch.arange()
one_to_ten = torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
torch.arange(start=0, end=1000, step=33)

tensor([  0,  33,  66,  99, 132, 165, 198, 231, 264, 297, 330, 363, 396, 429,
        462, 495, 528, 561, 594, 627, 660, 693, 726, 759, 792, 825, 858, 891,
        924, 957, 990])

In [24]:
# Creating tensors-like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes
**Note**: Datatypes is on of the big 3 problems u will run into
1. Tensor not right datatypes
2. Tensors not right shape
3. Tensor not on the right device

In [46]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.2, 6.1, 9.3],
                               dtype=None,            # What datatype is the tensor (float_32, float_16, ...)
                               device=None,           # What device is your tensor on
                               requires_grad=False)   # Track the gradiance
float_32_tensor

tensor([3.2000, 6.1000, 9.3000])

In [47]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3.1992, 6.1016, 9.2969], dtype=torch.float16)

In [48]:
float_16_tensor * float_32_tensor

tensor([10.2375, 37.2195, 86.4609])

## Getting Information from Tensors (attributes)

1. Datatype: tensor:dtype
2. Shape: tensor.shape
3. Device: tensor-device

In [55]:
tensor = torch.rand(3,4)
tensor

tensor([[0.8535, 0.3330, 0.9640, 0.3834],
        [0.2542, 0.2655, 0.8855, 0.7281],
        [0.8921, 0.6476, 0.9549, 0.0871]])

In [56]:
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Shape of tensor: {tensor.shape, tensor.size()}")
print(f"Device of tensor: {tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: (torch.Size([3, 4]), torch.Size([3, 4]))
Device of tensor: cpu


## Manipulating Tensors (tensor operations)

Tensor operations include:
1. +
2. -
3. *
4. /
5. Matrix multiplications

In [62]:
tensor = torch.tensor([1,2,3])

# Addition
tensor + 10

tensor([11, 12, 13])

In [63]:
# Multiply
tensor * 10

tensor([10, 20, 30])

In [64]:
# Subtraction
tensor - 10

tensor([-9, -8, -7])

In [67]:
# Division
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [68]:
# Buildup functions
tensor.add(10), tensor.sub(10), tensor.mul(10), tensor.div(10)

(tensor([11, 12, 13]),
 tensor([-9, -8, -7]),
 tensor([10, 20, 30]),
 tensor([0.1000, 0.2000, 0.3000]))

In [69]:
# Matric multiplion
# 2 Ways

In [74]:
# 1. Elemento-wise multiplication

print(tensor, "*", tensor)
print("Equals: ", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:  tensor([1, 4, 9])


In [75]:
# 2. Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [77]:
%%time
values = 0
for i in range(len(tensor)):
  values += tensor[i] * tensor[i]
values

CPU times: user 820 µs, sys: 0 ns, total: 820 µs
Wall time: 694 µs


tensor(14)

In [78]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 369 µs, sys: 17 µs, total: 386 µs
Wall time: 287 µs


tensor(14)