In [61]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


## Introduccion a Tensors


In [62]:

#scalar
scalar = torch.tensor(7)
scalar #Objeto tipo tensor

tensor(7)

In [63]:
scalar.ndim #Devuelve las dimensiones del tensor

0

In [64]:
scalar.item() #Devuelve el elementos como integer

7

In [65]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [66]:
vector.ndim

1

In [67]:
vector.shape

torch.Size([2])

In [68]:
# Matrix
MATRIX = torch.tensor([[7,7],
                      [8,8]])
MATRIX

tensor([[7, 7],
        [8, 8]])

In [69]:
MATRIX.ndim

2

In [70]:
MATRIX[0]

tensor([7, 7])

In [71]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [72]:
TENSOR.ndim

3

In [73]:
TENSOR.shape

torch.Size([1, 3, 3])

In [74]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [75]:
### LOS TENSORs te devuelven matrices al indexar, las matrices te devuelven vectores y los vectores devuelven scalares

## Random Tensors

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [76]:
# Create a random tensor of shape/size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8852, 0.4320, 0.5458, 0.5846],
        [0.1908, 0.0716, 0.3846, 0.6537],
        [0.2284, 0.0729, 0.5162, 0.6873]])

In [77]:
# Create a random tensor with similar shape to an imagen tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)

## Zeros and Ones

In [78]:
### Create a tensor of all zeros
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [79]:
### Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [80]:
ones.dtype #Default tensor type

torch.float32

## Create a range of tensor and tensors-like

In [81]:
# Use torch.arange()
one_to_ten = torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
torch.arange(start=0, end=1000, step=33)

tensor([  0,  33,  66,  99, 132, 165, 198, 231, 264, 297, 330, 363, 396, 429,
        462, 495, 528, 561, 594, 627, 660, 693, 726, 759, 792, 825, 858, 891,
        924, 957, 990])

In [83]:
# Creating tensors-like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes
**Note**: Datatypes is on of the big 3 problems u will run into
1. Tensor not right datatypes
2. Tensors not right shape
3. Tensor not on the right device

In [84]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.2, 6.1, 9.3],
                               dtype=None,            # What datatype is the tensor (float_32, float_16, ...)
                               device=None,           # What device is your tensor on
                               requires_grad=False)   # Track the gradiance
float_32_tensor

tensor([3.2000, 6.1000, 9.3000])

In [85]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3.1992, 6.1016, 9.2969], dtype=torch.float16)

In [86]:
float_16_tensor * float_32_tensor

tensor([10.2375, 37.2195, 86.4609])

## Getting Information from Tensors (attributes)

1. Datatype: tensor:dtype
2. Shape: tensor.shape
3. Device: tensor-device

In [87]:
tensor = torch.rand(3,4)
tensor

tensor([[0.8127, 0.7760, 0.4599, 0.9417],
        [0.5691, 0.5902, 0.3487, 0.1079],
        [0.8533, 0.7203, 0.1519, 0.1061]])

In [88]:
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Shape of tensor: {tensor.shape, tensor.size()}")
print(f"Device of tensor: {tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: (torch.Size([3, 4]), torch.Size([3, 4]))
Device of tensor: cpu


## Manipulating Tensors (tensor operations)

Tensor operations include:
1. +
2. -
3. *
4. /
5. Matrix multiplications

In [89]:
tensor = torch.tensor([1,2,3])

# Addition
tensor + 10

tensor([11, 12, 13])

In [90]:
# Multiply
tensor * 10

tensor([10, 20, 30])

In [91]:
# Subtraction
tensor - 10

tensor([-9, -8, -7])

In [92]:
# Division
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [93]:
# Buildup functions
tensor.add(10), tensor.sub(10), tensor.mul(10), tensor.div(10)

(tensor([11, 12, 13]),
 tensor([-9, -8, -7]),
 tensor([10, 20, 30]),
 tensor([0.1000, 0.2000, 0.3000]))

In [94]:
# Matric multiplion
# 2 Ways

In [95]:
# 1. Elemento-wise multiplication

print(tensor, "*", tensor)
print("Equals: ", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:  tensor([1, 4, 9])


In [96]:
# 2. Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [97]:
%%time
values = 0
for i in range(len(tensor)):
  values += tensor[i] * tensor[i]
values

CPU times: user 746 µs, sys: 0 ns, total: 746 µs
Wall time: 668 µs


tensor(14)

In [98]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 33 µs, sys: 0 ns, total: 33 µs
Wall time: 37.7 µs


tensor(14)

### Rules in Matrix multiplication

1. The **inner dimensions** must match:
  * `(3,2) @ (3,2)` wont work
  * `(2,3) @ (3,2)` will work
  * `(3,2) @ (2,3)` will work

2. The result matrix has the shape of the **outter dimensions**:
  * `(2,3) @ (3,2) -> (2,2) `
  * `(2,3) @ (3,4) -> (2,4)`

In [99]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[1.6469, 1.2439],
        [0.8574, 0.6644]])

In [100]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.7250, 0.4446, 0.2530],
        [0.9086, 0.5853, 0.3576],
        [0.3753, 0.2223, 0.1196]])

### One of the most common errors in deep learning

In [101]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])
# matmul wont work

In [102]:
# To fix this we can **Transpose**

tensor_B = tensor_B.T
tensor_B

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [103]:
torch.mm(tensor_A, tensor_B)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

## Finde the min, max, mean, sum, etc

In [104]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [105]:
# Min
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [106]:
# Max
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [107]:
# Mean
# note: necesita tensors de tipo float o complex
x.type(torch.float32).mean(), torch.mean(x.type(torch.float32))

(tensor(45.), tensor(45.))

In [108]:
# Sum
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

In [109]:
# Find the positional min and max

x.argmax(), x.argmin()

(tensor(9), tensor(0))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensor on top of each other (vstack) or side to side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input wirh dimensions permuted (swapperd) in a certain way

In [139]:
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [140]:
# Add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [141]:
# Change the view - maintains the original shape
z = x.view(9,1)
z, z.shape, x, x.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 torch.Size([9]))

In [142]:
z[0] = 5
z, x

(tensor([[5],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [147]:
#Stack on top (vshape)
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked, x_stacked.shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9]]),
 torch.Size([4, 9]))

In [148]:
#Stack on side (hshape)
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked, x_stacked.shape

(tensor([[5, 5, 5, 5],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [4, 4, 4, 4],
         [5, 5, 5, 5],
         [6, 6, 6, 6],
         [7, 7, 7, 7],
         [8, 8, 8, 8],
         [9, 9, 9, 9]]),
 torch.Size([9, 4]))

In [154]:
# Squeeze
x_squeezed = torch.squeeze(torch.zeros(1,9))
x_squeezed, x_squeezed.shape

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.]), torch.Size([9]))

In [168]:
# Unsqueeze
x_squeezed = torch.unsqueeze(torch.zeros(1, 9), 2)
x_squeezed, x_squeezed.shape

(tensor([[[0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.]]]),
 torch.Size([1, 9, 1]))

In [176]:
# Permute
x = torch.rand(224, 10, 3)
x.shape

torch.Size([224, 10, 3])

In [177]:
x_permuted = x.permute(2, 0, 1) # -> 2 to 0, 0 to 1 and 1 to 2
x_permuted.shape

torch.Size([3, 224, 10])

In [183]:
x[1, 0, 0] = 10000
x[1, 0, 0], x_permuted[0, 1, 0]

(tensor(10000.), tensor(10000.))