In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


## Introduccion a Tensors


In [2]:

#scalar
scalar = torch.tensor(7)
scalar #Objeto tipo tensor

tensor(7)

In [3]:
scalar.ndim #Devuelve las dimensiones del tensor

0

In [4]:
scalar.item() #Devuelve el elementos como integer

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,7],
                      [8,8]])
MATRIX

tensor([[7, 7],
        [8, 8]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 7])

In [11]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [15]:
### LOS TENSORs te devuelven matrices al indexar, las matrices te devuelven vectores y los vectores devuelven scalares

## Random Tensors

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [16]:
# Create a random tensor of shape/size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2709, 0.1517, 0.1516, 0.4662],
        [0.8872, 0.4641, 0.6379, 0.9783],
        [0.8297, 0.1203, 0.9031, 0.0862]])

In [17]:
# Create a random tensor with similar shape to an imagen tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)

## Zeros and Ones

In [18]:
### Create a tensor of all zeros
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
### Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype #Default tensor type

torch.float32

## Create a range of tensor and tensors-like

In [21]:
# Use torch.arange()
one_to_ten = torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
torch.arange(start=0, end=1000, step=33)

tensor([  0,  33,  66,  99, 132, 165, 198, 231, 264, 297, 330, 363, 396, 429,
        462, 495, 528, 561, 594, 627, 660, 693, 726, 759, 792, 825, 858, 891,
        924, 957, 990])

In [23]:
# Creating tensors-like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes
**Note**: Datatypes is on of the big 3 problems u will run into
1. Tensor not right datatypes
2. Tensors not right shape
3. Tensor not on the right device

In [24]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.2, 6.1, 9.3],
                               dtype=None,            # What datatype is the tensor (float_32, float_16, ...)
                               device=None,           # What device is your tensor on
                               requires_grad=False)   # Track the gradiance
float_32_tensor

tensor([3.2000, 6.1000, 9.3000])

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3.1992, 6.1016, 9.2969], dtype=torch.float16)

In [26]:
float_16_tensor * float_32_tensor

tensor([10.2375, 37.2195, 86.4609])

## Getting Information from Tensors (attributes)

1. Datatype: tensor:dtype
2. Shape: tensor.shape
3. Device: tensor-device

In [27]:
tensor = torch.rand(3,4)
tensor

tensor([[0.2001, 0.2575, 0.6365, 0.3912],
        [0.0112, 0.0897, 0.0432, 0.1998],
        [0.4773, 0.0867, 0.4348, 0.4736]])

In [28]:
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Shape of tensor: {tensor.shape, tensor.size()}")
print(f"Device of tensor: {tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: (torch.Size([3, 4]), torch.Size([3, 4]))
Device of tensor: cpu


## Manipulating Tensors (tensor operations)

Tensor operations include:
1. +
2. -
3. *
4. /
5. Matrix multiplications

In [29]:
tensor = torch.tensor([1,2,3])

# Addition
tensor + 10

tensor([11, 12, 13])

In [30]:
# Multiply
tensor * 10

tensor([10, 20, 30])

In [31]:
# Subtraction
tensor - 10

tensor([-9, -8, -7])

In [32]:
# Division
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [33]:
# Buildup functions
tensor.add(10), tensor.sub(10), tensor.mul(10), tensor.div(10)

(tensor([11, 12, 13]),
 tensor([-9, -8, -7]),
 tensor([10, 20, 30]),
 tensor([0.1000, 0.2000, 0.3000]))

In [34]:
# Matric multiplion
# 2 Ways

In [35]:
# 1. Elemento-wise multiplication

print(tensor, "*", tensor)
print("Equals: ", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:  tensor([1, 4, 9])


In [36]:
# 2. Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [37]:
%%time
values = 0
for i in range(len(tensor)):
  values += tensor[i] * tensor[i]
values

CPU times: user 735 µs, sys: 0 ns, total: 735 µs
Wall time: 884 µs


tensor(14)

In [38]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 35 µs, sys: 6 µs, total: 41 µs
Wall time: 45.5 µs


tensor(14)

### Rules in Matrix multiplication

1. The **inner dimensions** must match:
  * `(3,2) @ (3,2)` wont work
  * `(2,3) @ (3,2)` will work
  * `(3,2) @ (2,3)` will work

2. The result matrix has the shape of the **outter dimensions**:
  * `(2,3) @ (3,2) -> (2,2) `
  * `(2,3) @ (3,4) -> (2,4)`

In [39]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.1502, 0.1551],
        [0.3827, 0.7922]])

In [40]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.7109, 0.4267, 0.3190],
        [0.3320, 0.0596, 0.1003],
        [0.2602, 0.3464, 0.1830]])

### One of the most common errors in deep learning

In [41]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])
# matmul wont work

In [42]:
# To fix this we can **Transpose**

tensor_B = tensor_B.T
tensor_B

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [43]:
torch.mm(tensor_A, tensor_B)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

## Finde the min, max, mean, sum, etc

In [44]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [45]:
# Min
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [46]:
# Max
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [47]:
# Mean
# note: necesita tensors de tipo float o complex
x.type(torch.float32).mean(), torch.mean(x.type(torch.float32))

(tensor(45.), tensor(45.))

In [48]:
# Sum
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

In [49]:
# Find the positional min and max

x.argmax(), x.argmin()

(tensor(9), tensor(0))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensor on top of each other (vstack) or side to side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input wirh dimensions permuted (swapperd) in a certain way

In [50]:
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [51]:
# Add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [52]:
# Change the view - maintains the original shape
z = x.view(9,1)
z, z.shape, x, x.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 torch.Size([9]))

In [53]:
z[0] = 5
z, x

(tensor([[5],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [54]:
#Stack on top (vshape)
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked, x_stacked.shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9]]),
 torch.Size([4, 9]))

In [55]:
#Stack on side (hshape)
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked, x_stacked.shape

(tensor([[5, 5, 5, 5],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [4, 4, 4, 4],
         [5, 5, 5, 5],
         [6, 6, 6, 6],
         [7, 7, 7, 7],
         [8, 8, 8, 8],
         [9, 9, 9, 9]]),
 torch.Size([9, 4]))

In [56]:
# Squeeze
x_squeezed = torch.squeeze(torch.zeros(1,9))
x_squeezed, x_squeezed.shape

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.]), torch.Size([9]))

In [57]:
# Unsqueeze
x_squeezed = torch.unsqueeze(torch.zeros(1, 9), 2)
x_squeezed, x_squeezed.shape

(tensor([[[0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.]]]),
 torch.Size([1, 9, 1]))

In [58]:
# Permute
x = torch.rand(224, 10, 3)
x.shape

torch.Size([224, 10, 3])

In [59]:
x_permuted = x.permute(2, 0, 1) # -> 2 to 0, 0 to 1 and 1 to 2
x_permuted.shape

torch.Size([3, 224, 10])

In [60]:
x[1, 0, 0] = 10000
x[1, 0, 0], x_permuted[0, 1, 0]

(tensor(10000.), tensor(10000.))

In [61]:
# They refere to the same "object", so if u change it, it will change in both

## Indexing

Indexing with Pytorch is similar to indexin with NumPy

In [62]:
x = torch.arange(1, 19).reshape(2,3,3)
x, x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 torch.Size([2, 3, 3]))

In [63]:
# Lets index
x[0], x[0, 0], x[0, 0, 0], x[0,2,2]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1),
 tensor(9))

In [64]:
# U can also use the ":", it gives al the elements of the target dimension
x[:], x[0, :, 0], x[0, :, 2]

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 tensor([1, 4, 7]),
 tensor([3, 6, 9]))

In [65]:
x[:, :, 1]

tensor([[ 2,  5,  8],
        [11, 14, 17]])

## Pythorch tensor & Numpy

* Data in NumPy -> want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [96]:
# Numpy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [97]:
# Change the value of array
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [98]:
# Tensor to Numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [99]:
# Change the values of array
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility - trying to take random out of random

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**



In [133]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0880, 0.2116, 0.7195, 0.2623],
        [0.0998, 0.5419, 0.4709, 0.9844],
        [0.8875, 0.3055, 0.0658, 0.2326]])
tensor([[0.1972, 0.9177, 0.9215, 0.6043],
        [0.6824, 0.0801, 0.0650, 0.4446],
        [0.6569, 0.3162, 0.0543, 0.3740]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [135]:
# Set the seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
