In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


## Introduccion a Tensors


In [2]:

#scalar
scalar = torch.tensor(7)
scalar #Objeto tipo tensor

tensor(7)

In [3]:
scalar.ndim #Devuelve las dimensiones del tensor

0

In [4]:
scalar.item() #Devuelve el elementos como integer

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,7],
                      [8,8]])
MATRIX

tensor([[7, 7],
        [8, 8]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 7])

In [11]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [15]:
### LOS TENSORs te devuelven matrices al indexar, las matrices te devuelven vectores y los vectores devuelven scalares

## Random Tensors

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [16]:
# Create a random tensor of shape/size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7738, 0.1111, 0.7738, 0.5023],
        [0.1020, 0.2432, 0.5324, 0.8572],
        [0.1070, 0.5964, 0.1975, 0.3475]])

In [17]:
# Create a random tensor with similar shape to an imagen tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)

## Zeros and Ones

In [18]:
### Create a tensor of all zeros
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
### Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype #Default tensor type

torch.float32

## Create a range of tensor and tensors-like

In [21]:
# Use torch.arange()
one_to_ten = torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
torch.arange(start=0, end=1000, step=33)

tensor([  0,  33,  66,  99, 132, 165, 198, 231, 264, 297, 330, 363, 396, 429,
        462, 495, 528, 561, 594, 627, 660, 693, 726, 759, 792, 825, 858, 891,
        924, 957, 990])

In [23]:
# Creating tensors-like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes
**Note**: Datatypes is on of the big 3 problems u will run into
1. Tensor not right datatypes
2. Tensors not right shape
3. Tensor not on the right device

In [24]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.2, 6.1, 9.3],
                               dtype=None,            # What datatype is the tensor (float_32, float_16, ...)
                               device=None,           # What device is your tensor on
                               requires_grad=False)   # Track the gradiance
float_32_tensor

tensor([3.2000, 6.1000, 9.3000])

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3.1992, 6.1016, 9.2969], dtype=torch.float16)

In [26]:
float_16_tensor * float_32_tensor

tensor([10.2375, 37.2195, 86.4609])

## Getting Information from Tensors (attributes)

1. Datatype: tensor:dtype
2. Shape: tensor.shape
3. Device: tensor-device

In [27]:
tensor = torch.rand(3,4)
tensor

tensor([[0.1427, 0.8121, 0.2250, 0.0418],
        [0.7577, 0.6110, 0.7281, 0.8324],
        [0.3542, 0.1421, 0.9572, 0.1919]])

In [28]:
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Shape of tensor: {tensor.shape, tensor.size()}")
print(f"Device of tensor: {tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: (torch.Size([3, 4]), torch.Size([3, 4]))
Device of tensor: cpu


## Manipulating Tensors (tensor operations)

Tensor operations include:
1. +
2. -
3. *
4. /
5. Matrix multiplications

In [29]:
tensor = torch.tensor([1,2,3])

# Addition
tensor + 10

tensor([11, 12, 13])

In [30]:
# Multiply
tensor * 10

tensor([10, 20, 30])

In [31]:
# Subtraction
tensor - 10

tensor([-9, -8, -7])

In [32]:
# Division
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [33]:
# Buildup functions
tensor.add(10), tensor.sub(10), tensor.mul(10), tensor.div(10)

(tensor([11, 12, 13]),
 tensor([-9, -8, -7]),
 tensor([10, 20, 30]),
 tensor([0.1000, 0.2000, 0.3000]))

In [34]:
# Matric multiplion
# 2 Ways

In [35]:
# 1. Elemento-wise multiplication

print(tensor, "*", tensor)
print("Equals: ", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:  tensor([1, 4, 9])


In [36]:
# 2. Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [37]:
%%time
values = 0
for i in range(len(tensor)):
  values += tensor[i] * tensor[i]
values

CPU times: user 891 µs, sys: 0 ns, total: 891 µs
Wall time: 752 µs


tensor(14)

In [38]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 30 µs, sys: 5 µs, total: 35 µs
Wall time: 37.9 µs


tensor(14)

### Rules in Matrix multiplication

1. The **inner dimensions** must match:
  * `(3,2) @ (3,2)` wont work
  * `(2,3) @ (3,2)` will work
  * `(3,2) @ (2,3)` will work

2. The result matrix has the shape of the **outter dimensions**:
  * `(2,3) @ (3,2) -> (2,2) `
  * `(2,3) @ (3,4) -> (2,4)`

In [39]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.8068, 0.2027],
        [0.3626, 0.1311]])

In [40]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.6353, 0.3989, 0.8469],
        [0.8042, 0.6981, 0.8838],
        [0.7733, 0.5598, 0.9584]])

### One of the most common errors in deep learning

In [41]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])
# matmul wont work

In [42]:
# To fix this we can **Transpose**

tensor_B = tensor_B.T
tensor_B

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [43]:
torch.mm(tensor_A, tensor_B)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

## Finde the min, max, mean, sum, etc

In [44]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [45]:
# Min
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [46]:
# Max
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [47]:
# Mean
# note: necesita tensors de tipo float o complex
x.type(torch.float32).mean(), torch.mean(x.type(torch.float32))

(tensor(45.), tensor(45.))

In [48]:
# Sum
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

In [49]:
# Find the positional min and max

x.argmax(), x.argmin()

(tensor(9), tensor(0))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensor on top of each other (vstack) or side to side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input wirh dimensions permuted (swapperd) in a certain way

In [50]:
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [51]:
# Add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [52]:
# Change the view - maintains the original shape
z = x.view(9,1)
z, z.shape, x, x.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 torch.Size([9]))

In [53]:
z[0] = 5
z, x

(tensor([[5],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [54]:
#Stack on top (vshape)
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked, x_stacked.shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9]]),
 torch.Size([4, 9]))

In [55]:
#Stack on side (hshape)
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked, x_stacked.shape

(tensor([[5, 5, 5, 5],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [4, 4, 4, 4],
         [5, 5, 5, 5],
         [6, 6, 6, 6],
         [7, 7, 7, 7],
         [8, 8, 8, 8],
         [9, 9, 9, 9]]),
 torch.Size([9, 4]))

In [56]:
# Squeeze
x_squeezed = torch.squeeze(torch.zeros(1,9))
x_squeezed, x_squeezed.shape

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.]), torch.Size([9]))

In [57]:
# Unsqueeze
x_squeezed = torch.unsqueeze(torch.zeros(1, 9), 2)
x_squeezed, x_squeezed.shape

(tensor([[[0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.]]]),
 torch.Size([1, 9, 1]))

In [58]:
# Permute
x = torch.rand(224, 10, 3)
x.shape

torch.Size([224, 10, 3])

In [59]:
x_permuted = x.permute(2, 0, 1) # -> 2 to 0, 0 to 1 and 1 to 2
x_permuted.shape

torch.Size([3, 224, 10])

In [60]:
x[1, 0, 0] = 10000
x[1, 0, 0], x_permuted[0, 1, 0]

(tensor(10000.), tensor(10000.))

In [61]:
# They refere to the same "object", so if u change it, it will change in both

## Indexing

Indexing with Pytorch is similar to indexin with NumPy

In [62]:
x = torch.arange(1, 19).reshape(2,3,3)
x, x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 torch.Size([2, 3, 3]))

In [63]:
# Lets index
x[0], x[0, 0], x[0, 0, 0], x[0,2,2]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1),
 tensor(9))

In [64]:
# U can also use the ":", it gives al the elements of the target dimension
x[:], x[0, :, 0], x[0, :, 2]

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 tensor([1, 4, 7]),
 tensor([3, 6, 9]))

In [65]:
x[:, :, 1]

tensor([[ 2,  5,  8],
        [11, 14, 17]])

## Pythorch tensor & Numpy

* Data in NumPy -> want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [66]:
# Numpy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [67]:
# Change the value of array
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [68]:
# Tensor to Numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [69]:
# Change the values of array
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility - trying to take random out of random

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**



In [70]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4984, 0.1935, 0.6054, 0.9557],
        [0.3582, 0.7064, 0.9450, 0.6872],
        [0.0413, 0.7052, 0.5176, 0.1375]])
tensor([[0.5874, 0.2518, 0.4950, 0.6059],
        [0.4513, 0.6448, 0.4005, 0.8015],
        [0.8424, 0.8073, 0.8766, 0.3631]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [71]:
# Set the seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on GPUs

GPUs = Faster compurter on numbers.

### Getting a GPU

1. Use a google colab
2. Use your own GPU - setup and investment (lots of options)
3. Use cloud computing (google cloud, AWS, Azure)

Entorno de Ejecucion - Cambiar tipo de entorno de Ejecucion - GPU

In [73]:
!nvidia-smi

Fri May  9 12:08:04 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   40C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [74]:
# Check for GPU access with PyTorch

torch.cuda.is_available()

True

In [77]:
# Setup device agnostic code (good practice)

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [78]:
# Count number of devices
torch.cuda.device_count()

1

### Putting tensors (and models) on the GPU

- Cant converto tensors to numpy if the tensor is in the GPU

In [86]:
tensor = torch.tensor([1,2,3])

tensor.device

device(type='cpu')

In [92]:
# Moving tensor to a GPU IF AVAILABLE
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [94]:
# Moving tensors back to the CPU
tensor_to_cpu = tensor_on_gpu.cpu()
tensor_to_cpu.device

device(type='cpu')

## Exercises and Extra-curriculum

https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

### 1.Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.

### 2. Create a random tensor with shape (7, 7).

In [96]:
import torch

tensor_2 = torch.rand(7,7)
tensor_2

tensor([[0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666, 0.9811, 0.0874, 0.0041],
        [0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035, 0.3813, 0.7860, 0.1115, 0.2477],
        [0.6524, 0.6057, 0.3725, 0.7980, 0.8399, 0.1374, 0.2331],
        [0.9578, 0.3313, 0.3227, 0.0162, 0.2137, 0.6249, 0.4340],
        [0.1371, 0.5117, 0.1585, 0.0758, 0.2247, 0.0624, 0.1816]])

### 3.Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [97]:
tensor_3 = torch.rand(1,7)
tensor_3

tensor([[0.9998, 0.5944, 0.6541, 0.0337, 0.1716, 0.3336, 0.5782]])

In [101]:
tensor_3 = tensor_3.T
torch.matmul(tensor_2, tensor_3)

tensor([[1.2748],
        [1.1652],
        [1.0182],
        [1.7959],
        [1.6076],
        [1.8623],
        [0.7118]])

### 4.Set the random seed to 0 and do exercises 2 & 3 over again.

In [103]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor_2 = torch.rand(7,7)
tensor_2

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [104]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor_3 = torch.rand(1,7)
tensor_3

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

In [105]:
tensor_3 = tensor_3.T
torch.matmul(tensor_2, tensor_3)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5.Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [109]:
RANDOM_SEED = 1234
torch.cuda.manual_seed(RANDOM_SEED)

### 6.Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [113]:
device = "cuda" if torch.cuda.is_available else "cpu"
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)

tensor_61 = torch.rand(2,3, device=device)

torch.manual_seed(RANDOM_SEED)
tensor_62 = torch.rand(2,3, device=device)

print(tensor_61)
print(tensor_62)

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')


### 7.Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [118]:
tensor_7 = torch.mm(tensor_61, tensor_62.T)
tensor_7

tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')

### 8.Find the maximum and minimum values of the output of 7.

In [121]:
print(tensor_7.min(), tensor_7.max())

tensor(0.8358, device='cuda:0') tensor(1.4578, device='cuda:0')


### 9.Find the maximum and minimum index values of the output of 7.

In [122]:
print(tensor_7.argmin(), tensor_7.argmax())

tensor(1, device='cuda:0') tensor(3, device='cuda:0')


### 10.Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [123]:
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)

tensor_10 = torch.rand(1, 1, 1, 10)
tensor_10

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

In [126]:
tensor_10_squeezed = tensor_10.squeeze()

#First tensor
print(f"Tensor: {tensor_10}")
print(f"Shape: {tensor_10.size()}")

#Second tensor
print(f"Tensor: {tensor_10_squeezed}")
print(f"Shape: {tensor_10_squeezed.size()}")

Tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Shape: torch.Size([1, 1, 1, 10])
Tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Shape: torch.Size([10])
