In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


## Introduccion a Tensors


In [30]:

#scalar
scalar = torch.tensor(7)
scalar #Objeto tipo tensor

tensor(7)

In [8]:
scalar.ndim #Devuelve las dimensiones del tensor

0

In [9]:
scalar.item() #Devuelve el elementos como integer

7

In [10]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [15]:
# Matrix
MATRIX = torch.tensor([[7,7],
                      [8,8]])
MATRIX

tensor([[7, 7],
        [8, 8]])

In [16]:
MATRIX.ndim

2

In [17]:
MATRIX[0]

tensor([7, 7])

In [23]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [24]:
TENSOR.ndim

3

In [25]:
TENSOR.shape

torch.Size([1, 3, 3])

In [26]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [28]:
### LOS TENSORs te devuelven matrices al indexar, las matrices te devuelven vectores y los vectores devuelven scalares

## Random Tensors

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [35]:
# Create a random tensor of shape/size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2577, 0.9130, 0.3816, 0.1750],
        [0.4199, 0.5274, 0.8375, 0.1360],
        [0.2744, 0.2699, 0.8109, 0.0538]])

In [36]:
# Create a random tensor with similar shape to an imagen tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)

## Zeros and Ones

In [66]:
### Create a tensor of all zeros
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [67]:
### Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [68]:
ones.dtype #Default tensor type

torch.float32

## Create a range of tensor and tensors-like

In [74]:
# Use torch.arange()
one_to_ten = torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
torch.arange(start=0, end=1000, step=33)

tensor([  0,  33,  66,  99, 132, 165, 198, 231, 264, 297, 330, 363, 396, 429,
        462, 495, 528, 561, 594, 627, 660, 693, 726, 759, 792, 825, 858, 891,
        924, 957, 990])

In [77]:
# Creating tensors-like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])